# Generated by Django 3.0.3 on 2020-03-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200303_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='link',
            field=models.FileField(blank=True, null=True, upload_to='backend.File/bytes/filename/mimetype'),
        ),
    ]
