# Generated by Django 3.0.3 on 2020-05-21 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200325_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Markup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Не указано', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='entity',
            name='origin_text',
        ),
        migrations.AlterField(
            model_name='author',
            name='place_of_birth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='place_of_birth', to='backend.Place'),
        ),
        migrations.CreateModel(
            name='MarkupToText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.Corpus')),
                ('text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.Resource')),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='markup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='markup', to='backend.Markup'),
        ),
    ]
