# Generated by Django 3.0.3 on 2020-05-21 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200521_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markuptotext',
            name='markup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.Markup'),
        ),
    ]
