export const GET_TESTS = "GET_TESTS"

export const GET_RESOURCES = "GET_RESOURCES"
export const GET_RESOURCE = "GET_RESOURCE"
export const GET_RESOURCE_TYPES = "GET_RESOURCE_TYPES"
export const GET_RESOURCE_WORKSPACE = "GET_RESOURCE_WORKSPACE"

export const GET_PIN_WINDOW = "GET_PIN_WINDOW"

export const GET_CORPUSES = "GET_CORPUSES"
export const GET_CORPUS = "GET_CORPUS"
export const GET_CORPUS_RESOURCES = "GET_CORPUS_RESOURCES"
export const GET_CORPUS_AUTHORS = "GET_CORPUS_AUTHORS"
export const GET_CORPUS_PLACES = "GET_CORPUS_PLACES"
export const GET_CORPUS_OBJECTS = "GET_CORPUS_OBJECTS"
export const GET_CORPUS_CLASSES = "GET_CORPUS_CLASSES"

export const GET_AUTHORS = "GET_AUTHORS"
export const GET_AUTHOR = "GET_AUTHOR"

export const CREATE_WINDOW = "CREATE_WINDOW"

export const GET_PLACE = "GET_PLACE"
export const GET_PLACES = "GET_PLACES"

export const GET_CLASS = "GET_CLASS"
export const GET_CLASSES = "GET_CLASSES"

export const GET_OBJECT = "GET_OBJECT"
export const GET_OBJECTS = "GET_OBJECTS"






