export const GET_TESTS = "GET_TESTS"

export const GET_RESOURCES = "GET_RESOURCES"
export const GET_RESOURCE = "GET_RESOURCE"
export const GET_RESOURCE_TYPES = "GET_RESOURCE_TYPES"
export const CREATE_RESOURCE_TYPE = 'CREATE_RESOURCE_TYPE';
export const GET_RESOURCE_WORKSPACE = "GET_RESOURCE_WORKSPACE"
export const UPDATE_RESOURCE = "UPDATE_RESOURCE"
export const DELETE_RESOURCE = "DELETE_RESOURCE"



export const GET_PIN_WINDOW = "GET_PIN_WINDOW"

export const GET_CORPUSES = "GET_CORPUSES"
export const CREATE_CORPUS = "CREATE_CORPUS"
export const DELETE_CORPUS = "DELETE_CORPUS"
export const GET_CORPUS = "GET_CORPUS"
export const UPDATE_CORPUS = "UPDATE_CORPUS"
export const GET_CORPUS_RESOURCES = "GET_CORPUS_RESOURCES"
export const GET_CORPUS_AUTHORS = "GET_CORPUS_AUTHORS"
export const GET_CORPUS_PLACES = "GET_CORPUS_PLACES"
export const GET_CORPUS_OBJECTS = "GET_CORPUS_OBJECTS"
export const GET_CORPUS_CLASSES = "GET_CORPUS_CLASSES"

export const GET_AUTHORS = "GET_AUTHORS"
export const GET_AUTHOR = "GET_AUTHOR"
export const UPDATE_AUTHOR = "UPDATE_AUTHOR"
export const CREATE_AUTHOR = "CREATE_AUTHOR"
export const DELETE_AUTHOR = "DELETE_AUTHOR"


export const CREATE_WINDOW = "CREATE_WINDOW"

export const GET_PLACE = "GET_PLACE"
export const GET_PLACES = "GET_PLACES"
export const DELETE_PLACE = "DELETE_PLACE"
export const UPDATE_PLACE = "UPDATE_PLACE"
export const CREATE_PLACE = "CREATE_PLACE"


export const GET_CLASS = "GET_CLASS"
export const DELETE_CLASS = "DELETE_CLASS"
export const GET_CLASSES = "GET_CLASSES"
export const UPDATE_CLASS = "UPDATE_CLASS"
export const CREATE_CLASS = "CREATE_CLASS"


export const GET_OBJECT = "GET_OBJECT"
export const DELETE_OBJECT = "DELETE_OBJECT"
export const GET_OBJECTS = "GET_OBJECTS"
export const UPDATE_OBJECT = "UPDATE_OBJECT"
export const CREATE_OBJECT = "CREATE_OBJECT"

export const CREATE_RELATION = "CREATE_RELATION"
export const DELETE_RELATION = "DELETE_RELATION"
export const GET_RELATIONS_FROM_OBJECT = "GET_RELATIONS_FROM_OBJECT"
export const GET_RELATIONS_FROM_TEXT = "GET_RELATIONS_FROM_TEXT"


export const GET_MARKUPS_TEXT = "GET_MARKUPS_TEXT"
export const GET_MARKUP_ENTITES = "GET_MARKUP_ENTITES"
export const CREATE_MARKUP = "CREATE_MARKUP"
export const DELETE_MARKUP = "DELETE_MARKUP"





export const ADD_ENTITY = "ADD_ENTITY"
export const DELETE_ENTITY = "DELETE_ENTITY"
export const GET_ENTITIES_TEXT = "GET_ENTITIES_TEXT"
export const GET_ENTITIES_OBJECT = "GET_ENTITIES_OBJECT"

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const GET_ERRORS = 'GET_ERRORS';








